apiVersion: v1
kind: Service
metadata:
  name: biocad-web-service
spec:
  type: NodePort
  selector:
    app: biocad-web
  ports:
    - protocol: TCP
      port: 32777  
      targetPort: 32777
      nodePort: 32000
